// Project Configuration for project-12
window.portfolioProjects = window.portfolioProjects || {};
window.portfolioProjects['project-12'] = {
  title: "Restoration of Kayakoy Upper Church ",
  year: "2025",
  location: "Rome, Italy",
  category: "planning",
  timeline: "2020s",
  coverImage: "1.webp", // Name of the image file to show as thumbnail on homepage
  description: "This is a premium architectural development designed in the context of urban regeneration. Designed with high BIM standards, integrating Scan-to-BIM, parametric Revit elements, and detailed historical preservation workflows to yield high-efficiency structural models. You can easily edit this text or add details inside the projects/project-12/project-data.js file.",
  images: [
    "1.webp",
    "2.webp",
    "3.webp",
    "4.webp",
    "5.webp",
    "6.webp",
    "7.webp",
    "8.webp",
    "9.webp",
    "10.webp",
    "11.webp",
    "12.webp",
    "13.webp",
    "14.webp",
    "15.webp",
    "16.webp",
    "17.webp",
    "18.webp",
    "19.webp",
    "20.webp",
    "21.webp",
    "22.webp",
    "23.webp",
    "24.webp",
    "25.webp",
    "26.webp",
    "27.webp",
    "28.webp",
    "29.webp",
    "30.webp",
    "31.webp",
    "32.webp",
    "33.webp",
    "34.webp",
    "35.webp",
    "36.webp",
    "37.webp",
    "38.webp",
    "39.webp",
    "40.webp",
    "41.webp",
    "42.webp",
    "43.webp",
    "44.webp",
    "45.webp",
    "46.webp",
  ]
};
